apiVersion: v1
kind: Service
metadata:
  name: {{ include "devzone.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "devzone.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devzone.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "devzone.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devzone.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: DB_HOST
              value: "{{.Release.Name}}-postgresql"
            - name: DB_PORT
              value: {{ .Values.postgresql.postgresPort | quote }}
            - name: DB_DATABASE
              value: {{ .Values.postgresql.postgresDatabase | quote }}
            - name: DB_USERNAME
              value: {{ .Values.postgresql.postgresUsername | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.postgresPassword | quote }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.port }}
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
